---
# Copyright 2015, HO Tech Co, Ltd.
# Author: Guan Ji Chen/HO Tech
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Copy vaneCloud horizon UI
  copy:
    src: vaneCloudUI/
    dest: /usr/local/lib/python2.7/dist-packages
    owner: root
    group: www-data

- name: Enable vaneCloud horizon UI theme
  lineinfile:
    dest: /etc/horizon/local_settings.py
    regexp: ^CUSTOM_THEME_PATH
    line: CUSTOM_THEME_PATH = "static/themes/vanecloud"

- name: Enable vaneCloud horizon UI theme - cont.
  lineinfile:
    dest: /etc/horizon/local_settings.py
    regexp: ^SITE_BRANDING
    line: SITE_BRANDING = "VaneCloud Dashboard"

- name: Compile vaneCloud horizon UI
  shell: horizon-manage.py collectstatic --noinput

- name: Compile vaneCloud horizon UI - cont.
  shell: horizon-manage.py compress --force

